name: download and compile Doxygen
on:
  workflow_call
env:
  DOXYGEN_VERSION: 1.9.4
jobs:
  install:
    runs-on: ubuntu-latest
    concurrency:
      group: linux-doxygen-cache
    steps:
      - uses: actions/cache/restore@v3
        id: cache-doxygen
        with:
          path: doxygen-bin-arc
          key: ${{ runner.os }}-doxygen-${{ env.DOXYGEN_VERSION }}
          lookup-only: true
          restore-keys: |
            ${{ runner.os }}-doxygen-

      - name: download and build Doxygen from SF binary archives
        if: steps.cache-doxygen.outputs.cache-hit != 'true'
        run: |
          mkdir doxygen-bin-arc && cd doxygen-bin-arc
          curl -L https://sourceforge.net/projects/doxygen/files/rel-$DOXYGEN_VERSION/doxygen-$DOXYGEN_VERSION.linux.bin.tar.gz > doxygen.tar.gz
          gunzip doxygen.tar.gz
          tar xf doxygen.tar
          mv doxygen-$DOXYGEN_VERSION doxygen
          cd doxygen
          make

      - uses: actions/cache/save@v3
        if: steps.cache-doxygen.outputs.cache-hit != 'true'
        with:
          path: doxygen-bin-arc
          key: ${{ steps.cache-doxygen.outputs.cache-primary-key }}
