name: build the documentation
on: [push, pull_request]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up python
        uses: actions/setup-python@v4
        with:
          cache: 'pip'
          cache-dependency-path: |
            requirements/development.txt
            requirements/production.txt

      - name: install dependencies and build extension module
        run: |
          sudo apt-get -y update
          sudo apt-get -y install graphviz libclang1-11 libclang-cpp11
          pip install -r requirements/development.txt
          pip install --editable .

      - name: cache Doxygen
        id: cache-doxygen
        uses: actions/cache@v3
        with:
          path: doxygen-bin-arc/doxygen.tar.gz
          key: ${{ runner.os }}-doxygen

      - name: download Doxygen from SF binary archives
        if: steps.cache-doxygen.outputs.cache-hit != 'true'
        run: |
          mkdir doxygen-bin-arc
          curl -L https://sourceforge.net/projects/doxygen/files/rel-$DOXYGEN_VERSION/doxygen-$DOXYGEN_VERSION.linux.bin.tar.gz > doxygen-bin-arc/doxygen.tar.gz

      - name: install Doxygen
        run: |
          cd doxygen-bin-arc
          gunzip doxygen.tar.gz
          tar xf doxygen.tar
          cd doxygen-$DOXYGEN_VERSION
          sudo make install

      - name: build the documentation
        run: |
          make html
          rm documentation/build/html/.buildinfo

      - uses: actions/upload-artifact@v2
        with:
          name: docs build artifacts
          path: |
            documentation/build/html
            examples/*/*/xml
