name: build the documentation
on: [push, pull_request]
env:
  DOXYGEN_VERSION: 1.9.4
jobs:
  cache-doxygen:
    uses: ./.github/workflows/cache_doxygen.yml

  build:
    needs: cache-doxygen
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up python
        uses: actions/setup-python@v4
        with:
          cache: 'pip'
          cache-dependency-path: |
            requirements/development.txt
            requirements/production.txt

      - name: install dependencies and build extension module
        run: |
          sudo apt-get -y update
          sudo apt-get -y install graphviz libclang1-11 libclang-cpp11
          pip install -r requirements/development.txt
          pip install --editable .

      - uses: actions/cache/restore@v3
        id: cache-doxygen
        with:
          path: doxygen-bin-arc
          fail-on-cache-miss: true
          key: ${{ runner.os }}-doxygen-${{ env.DOXYGEN_VERSION }}
          restore-keys: |
            ${{ runner.os }}-doxygen-
  
      - name: install Doxygen
        run: |
          cd doxygen-bin-arc/doxygen
          sudo make install

      - name: build the documentation
        run: |
          make html
          rm documentation/build/html/.buildinfo

      - uses: actions/upload-artifact@v2
        with:
          name: docs build artifacts
          path: |
            documentation/build/html
            examples/*/*/xml
